#ifndef GUARD_OBJECT_FUNCTIONS_H
#define GUARD_OBJECT_FUNCTIONS_H

/* Semantic C names mapped to original symbols still referenced by assembly. */
#define object_update_then_trigger_at_boundary_a sub_809C13C
#define object_update_then_trigger_at_boundary_b sub_809C1E8
#define object_update_then_trigger_at_boundary_c sub_809C570

#define object_on_visual_complete_command_0_and_continue sub_8132D4C
#define object_on_visual_complete_command_0_and_stop sub_8132D78
#define object_on_visual_complete_command_13_and_continue sub_81332BC
#define object_when_value80_clear_command_10 sub_8133CF0
#define object_on_visual_complete_select_animation_5_or_8 sub_8062F40
#define object_on_visual_complete_spawn_effect_151d sub_806533C
#define object_on_visual_complete_select_animation_5_or_7 sub_809A858
#define object_when_linked_visual_complete_play_sound_10f sub_810FD10
#define object_finish_linked_chain_when_poll_clear sub_811090C
#define object_start_animation_0a_with_sound_11b sub_81124D0
#define object_when_poll_clear_disable_and_finish sub_811448C
#define object_on_visual_complete_snap_to_owner_position sub_8110A30
#define object_start_nested_animation_4_sequence sub_811458C

#endif
