#ifndef GUARD_OBJECT_RUNTIME_LEAF_CALLBACKS_H
#define GUARD_OBJECT_RUNTIME_LEAF_CALLBACKS_H

#include "object/runtime_object.h"

#define object_move_left_until_screen_exit sub_8068074
#define object_start_animation_6_when_value80_clears sub_80680A0
#define object_move_left_and_down_until_screen_exit sub_806819C
#define object_move_left_fast_until_screen_exit sub_80687EC
#define object_repeat_animation_until_behavior_count_expires sub_806C800
#define object_finish_visual_and_stop_update sub_806CB3C
#define object_release_position_owner_and_continue sub_806E690

void object_move_left_until_screen_exit(struct RuntimeObject* object);
void object_start_animation_6_when_value80_clears(struct RuntimeObject* object);
void object_move_left_and_down_until_screen_exit(struct RuntimeObject* object);
void object_move_left_fast_until_screen_exit(struct RuntimeObject* object);
void object_repeat_animation_until_behavior_count_expires(
    struct RuntimeObject* object);
void object_finish_visual_and_stop_update(struct RuntimeObject* object);
s32 object_release_position_owner_and_continue(struct RuntimeObject* object);

#endif
