#ifndef GUARD_OBJECT_SMALL_STATE_HELPERS_H
#define GUARD_OBJECT_SMALL_STATE_HELPERS_H

#include "object/runtime_object.h"

#define object_when_link_chain_empty_start_animation_0c sub_8065ED4
#define object_move_right_and_fall_to_ground sub_8067A4C
#define object_restore_saved_update_on_flag_20 sub_80886BC
#define object_when_nested_link_ready_continue sub_811488C
#define object_stop_sound_11a_and_idle sub_8068EF4
#define object_sync_linked_position_and_stop_when_value80_clear sub_806E754
#define object_when_value80_clear_increment_value_a8 sub_8070510
#define object_stop_update sub_8070C84
#define object_when_value80_clear_mark_state_2 sub_8079320
#define object_state_get_value_source_byte6 sub_8083E78
#define object_when_visual_value21_clear_install_update sub_8087524
#define object_save_update_and_install_flag_wait_a sub_808862C
#define object_save_update_and_install_flag_wait_b sub_808863C
#define object_prepare_and_install_callback_808a201 sub_808A098
#define object_when_state_value113_clear_delay_16 sub_8112064
#define object_when_flags_38_clear_stop_and_clear_owner_state sub_8114790
#define object_prepare_and_clear_state_value113 sub_81147B4

void object_when_link_chain_empty_start_animation_0c(struct RuntimeObject* object);
void object_move_right_and_fall_to_ground(struct RuntimeObject* object);
void object_restore_saved_update_on_flag_20(struct RuntimeObject* object);
void object_when_nested_link_ready_continue(struct RuntimeObject* object);

#endif
