#ifndef GUARD_OBJECT_VERTICAL_MOTION_CALLBACKS_H
#define GUARD_OBJECT_VERTICAL_MOTION_CALLBACKS_H

#include "object/runtime_object.h"

#define object_advance_vertical_motion_to_animation_6_path_a sub_808EF1C
#define object_advance_vertical_motion_to_animation_6_path_b sub_808FF18
#define object_advance_vertical_motion_to_animation_6_path_c sub_8090528
#define object_advance_vertical_motion_to_animation_6_path_d sub_8090894
#define object_advance_vertical_motion_to_animation_6_path_e sub_8090C90
#define object_advance_vertical_motion_to_animation_6_path_f sub_8091E00
#define object_advance_vertical_motion_to_animation_6_path_g sub_8092F90
#define object_advance_vertical_motion_to_animation_6_path_h sub_809411C
#define object_advance_vertical_motion_to_animation_6_path_i sub_8094574
#define object_advance_vertical_motion_to_animation_6_path_j sub_80949CC
#define object_advance_vertical_motion_to_animation_6_path_k sub_8094E24
#define object_advance_vertical_motion_to_alternate_animation_6_path_a sub_8091E70
#define object_advance_vertical_motion_to_alternate_animation_6_path_b sub_8093000
#define object_advance_vertical_motion_to_alternate_animation_6_path_c sub_809418C
#define object_advance_vertical_motion_to_alternate_animation_6_path_d sub_80945E4
#define object_advance_vertical_motion_to_alternate_animation_6_path_e sub_8094A3C
#define object_advance_vertical_motion_to_alternate_animation_6_path_f sub_8094E94
#define object_land_on_state_floor_with_animation_8_path_a sub_8091EE0
#define object_land_on_state_floor_with_animation_8_path_b sub_8093070
#define object_land_on_state_floor_with_animation_8_path_c sub_80941FC
#define object_land_on_state_floor_with_animation_8_path_d sub_8094654
#define object_land_on_state_floor_with_animation_8_path_e sub_8094AAC
#define object_land_on_state_floor_with_animation_8_path_f sub_8094F04

#define DECLARE_VERTICAL_CALLBACK(name) void name(struct RuntimeObject* object)

DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_a);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_b);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_c);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_d);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_e);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_f);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_g);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_h);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_i);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_j);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_animation_6_path_k);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_a);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_b);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_c);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_d);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_e);
DECLARE_VERTICAL_CALLBACK(object_advance_vertical_motion_to_alternate_animation_6_path_f);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_a);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_b);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_c);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_d);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_e);
DECLARE_VERTICAL_CALLBACK(object_land_on_state_floor_with_animation_8_path_f);

#undef DECLARE_VERTICAL_CALLBACK

#endif
