#ifndef GUARD_MARIO_BROS_FUNCTIONS_H
#define GUARD_MARIO_BROS_FUNCTIONS_H

/* Semantic C names mapped to the original symbols still used by assembly. */
#define mario_bros_disable_interrupts sub_8F510CC
#define mario_bros_reset_platform_state sub_8F5C06C
#define mario_bros_fill_1024_halfwords sub_8F585B0
#define mario_bros_clear_tilemap_region sub_8F591F8
#define mario_bros_update_object_position_a sub_8F5F3C8
#define mario_bros_advance_object_state_if_ready sub_8F611DC
#define mario_bros_start_object_fall_unless_state_7 sub_8F63DB8
#define mario_bros_update_object_position_b sub_8F85D1C
#define mario_bros_begin_timed_animation sub_8F60458
#define mario_bros_run_object_command_12_a sub_8F6046C
#define mario_bros_run_object_command_12_b sub_8F60F60
#define mario_bros_run_object_command_12_c sub_8F62D28

#define mario_bros_transition_object_with_code_23 sub_8F6009C
#define mario_bros_transition_object_with_code_22 sub_8F60BA0
#define mario_bros_transition_object_with_code_21 sub_8F629AC

#define mario_bros_dispatch_sequence_callback_a sub_8F55174
#define mario_bros_dispatch_sequence_callback_b sub_8F55C90
#define mario_bros_dispatch_sequence_callback_c sub_8F5CBA4

#define mario_bros_dispatch_state_callback_a sub_8F5FC2C
#define mario_bros_dispatch_state_callback_b sub_8F63B14
#define mario_bros_dispatch_selector02_callback_a sub_8F6B860
#define mario_bros_dispatch_state_callback_c sub_8F6C0C8
#define mario_bros_dispatch_selector02_callback_c sub_8F6C8CC
#define mario_bros_dispatch_selector02_callback_d sub_8F6D148
#define mario_bros_select_value18_from_flag_bit2_a sub_8F65118
#define mario_bros_select_value18_from_flag_bit2_b sub_8F8BA6C
#define mario_bros_set_table_bits_from_frame_a sub_8F61E58
#define mario_bros_set_table_bits_from_frame_b sub_8F624CC
#define mario_bros_set_table_bits_from_frame_c sub_8F887AC
#define mario_bros_set_table_bits_from_frame_d sub_8F88E20
#define mario_bros_set_table_bits_from_clamped_frame_a sub_8F5FCAC
#define mario_bros_set_table_bits_from_clamped_frame_b sub_8F86600
#define mario_bros_advance_animation_pair sub_8F648AC
#define mario_bros_select_local_pair_a sub_8F5DFC4
#define mario_bros_select_local_pair_b sub_8F63D08
#define mario_bros_select_local_pair_c sub_8F84918
#define mario_bros_select_local_pair_d sub_8F8A65C
#define mario_bros_advance_animation_cycle_zero_based sub_8F5E604
#define mario_bros_advance_animation_cycle_one_based sub_8F63634
#define mario_bros_advance_animation_cycle_three_frame sub_8F64880
#define mario_bros_advance_animation_toggle_slow sub_8F65690

#define mario_bros_offset_and_clamp_coordinate_a sub_8F68504
#define mario_bros_offset_and_clamp_coordinate_b sub_8F8EE58
#define mario_bros_measure_horizontal_edge_distance_a sub_8F673B8
#define mario_bros_measure_horizontal_edge_distance_b sub_8F8DD0C

#define mario_bros_release_pool_object_a sub_8F5F060
#define mario_bros_release_pool_object_b sub_8F859B4
#define mario_bros_attach_pool_object_a sub_8F5D7F8
#define mario_bros_attach_pool_object_b sub_8F8414C
#define mario_bros_propagate_high_flag_a sub_8F61374
#define mario_bros_propagate_high_flag_b sub_8F87CC8
#define mario_bros_spawn_linked_object_a sub_8F64B3C
#define mario_bros_spawn_linked_object_b sub_8F8B490
#define mario_bros_reset_pool_record_a sub_8F5F1C8
#define mario_bros_reset_pool_record_b sub_8F85B1C
#define mario_bros_find_runtime_id_a sub_8F5F23C
#define mario_bros_find_runtime_id_b sub_8F85B90
#define mario_bros_find_spatial_object_id_a sub_8F5F73C
#define mario_bros_find_spatial_object_id_b sub_8F86090
#define mario_bros_dispatch_pool_objects_a sub_8F5F7C4
#define mario_bros_dispatch_pool_objects_b sub_08F86118

#define mario_bros_normalize_variant_a sub_8F66A40
#define mario_bros_normalize_variant_b sub_8F8D394
#define mario_bros_reset_state_controller_a sub_8F663B4
#define mario_bros_reset_state_controller_b sub_8F8CD08
#define mario_bros_emit_event_and_advance_sequence_a sub_8F58360
#define mario_bros_emit_event_and_advance_sequence_b sub_8F58398

#define mario_bros_call_object_callback_a sub_8F6E1F8
#define mario_bros_call_object_callback_b sub_8F6E20C
#define mario_bros_call_two_argument_callback sub_8F6F210
#define mario_bros_call_secondary_object_callback_a sub_8F94D78
#define mario_bros_call_secondary_object_callback_b sub_8F94D8C

#endif
